name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
      # Dummy envs to allow build without secrets
      NEXTAUTH_URL: http://127.0.0.1:3000
      NEXTAUTH_SECRET: ci-secret-placeholder
      SPOTIFY_CLIENT_ID: ci-client
      SPOTIFY_CLIENT_SECRET: ci-secret
      NEXT_PUBLIC_APP_URL: https://example.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prisma generate
        run: npm run prisma:generate

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
